#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display info about subdomains
# Func. to display info about subdomains
domain_information () {
  # Perform DNS lookup for the subdomain on specified domain
  line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
  # Extract relevant info. and print it
  echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

# Check the number of args passed to script
if [ "$#" == 1 ]
then
  # If only one arg passed, call domain info func
  # with predefined subdomain name
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" == 2 ]
then
  # If there is two arg calls, call domain info
  # function with provided subdomain name
  domain_information "$1" "$2"
fi

