#!/usr/bin/env bash
# Install and configure nginx
# to return 'Hello World!' on a GET request
# to /

function install_and_configure_nginx(){
    sudo apt-get update
    sudo apt-get -y install nginx
    service nginx start
    echo "Hello World!\n" > /tmp/var/www/html/index.html
    service nginx restart

}
install_and_configure_nginx;
