#!/usr/bin/env bash
# nginx web server listening on port 80
# Gives a page that contains the string "Hello World!"

sudo apt update -y
sudo apt install -y nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
