#!/usr/bin/env bash
# Configure Nginx server to /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "301 Moved Permanently" | sudo tee /var/www/html/301.html > /dev/null
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx reload
