#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get install -y nginx
service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html;
    location /redirect_me {
        return 301 https://https://www.youtube.com/watch?v=QH2-TGUlwu4 Permanent;
    }
    error_page 404 /404.html;
    location = /404.html{
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
