#!/usr/bin/env bash
# Configure the nginx server to listen to port 80
# Remove default nginx config file
rm /etc/nginx/sites-enabled/default
# Configure Nginx to listen to port 80 for all
# active ipv4 ips
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart nginx
service nginx restart
