#!/usr/bin/env bash
# displays content of the file /etc/passwd
#only display username, user id, and user home directory path

while read passwd; do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
