#!/usr/bin/env bash
# displays Best School 10 times.

k=1
while [ $k -lt 11 ]
do
    if [ $k = 4 ]
    then
        echo "bad luck"
    elif [ $k = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    let k+=1
done
