#!/usr/bin/env bash
#script that displays:

#content of current directory
#in list format
#where only part of the name after first dash displayed

list=$(ls)
for j in $list;do
 echo "$j" | cut -d '-' -f2
done
