#!/usr/bin/env bash
# Script use 7 line or less to run Nginx as Nginx
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
